# This secret will be used in the prepare-milvus-db-job.yaml for running the script for preparing sample data in the Milvus db. 
# Value from this secret will be used for authentication when pulling a Docker Image from ACR.
# Here we create a secret which holds a new generated value used for authentication to ACR. It can be created based on Service Principal credentials.

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.acrSecret.secretName }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.acrSecret.acrUrl }}": {
          "username": "{{ .Values.acrSecret.username }}",
          "password": "{{ .Values.acrSecret.password }}",
          "email": "{{ .Values.acrSecret.email }}",
          "auth": "{{ printf "%s:%s" .Values.acrSecret.username .Values.acrSecret.password | b64enc }}"
        }
      }
    }