apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
        - name: {{ .Values.deploymentName }}
          # URL of the image in ACR
          image: {{ .Values.image.url }}
          imagePullPolicy: Always
          command: ["python"]
          # Path to the Python script for starting the MCP Server
          args: ["{{ .Values.app.folderPath }}/{{ .Values.app.fileName }}"]
          ports:
            - containerPort: 8000
          env:
            - name: MILVUS_HOST
              value: {{ .Values.app.envVar.milvusHost }}
            - name: MILVUS_COLLECTION_NAME
              value: {{ .Values.app.envVar.milvusCollectionName }}
            - name: EMBEDDING_FIELD_NAME
              value: {{ .Values.app.envVar.embeddingFieldName }}
            - name: TEXT_FIELD_NAME
              value: {{ .Values.app.envVar.textFieldName }}
          {{- if .Values.scriptsMounting.enabled }}
          volumeMounts:
            # Mount a folder from a volume linked to Azure File share containing scripts to run.
            - name: scripts
              mountPath: {{ .Values.app.folderPath }}
              subPath: {{ .Values.scriptsMounting.volumePath }}
          {{- end}}
      # Secret for authentication when pulling image from ACR
      imagePullSecrets:
        - name: {{ .Values.acrSecret.secretName }}
      {{- if .Values.scriptsMounting.enabled }}
      # Volume linked to Azure File share containing scripts to run
      volumes:
        - name: scripts
          persistentVolumeClaim:
            claimName: {{ .Values.scriptsMounting.pvcName }}
      {{- end}}