apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentName }}
spec:
  selector:
    app: {{ .Values.deploymentName }}  # must match Deployment's pod labels
  ports:
    - port: 8000       # Service port (clients use this)
      targetPort: 8000 # Container port (from Deployment)
  type: ClusterIP