namespace: ai-agent             # Namespace where to deploy resources
deploymentName: mcp-server      # Name of the created Deployment (running the MCP server)
serviceName: mcp-server-service # Name of the created Service (linked to the Deployment)

# Parameters related to the image with the MCP Server
image:
  # url - URL of the image in the registry
  url: ${acr_url}/${mcp_server_image_name}:latest

# Parameters related to the Python app with the MCP Server
app:
  # path - Path in the image of the app
  fileName: mcp_server.py # Name of the file with the app to run
  folderPath: /app  # Path to the folder containing the app
  # Environment variables used by the app
  envVar:
    # milvusHost - This must be the name of the release of the prepare_milvus_db Helm chart.
    milvusHost: milvus
    milvusCollectionName: my_docs
    embeddingFieldName: embedding
    textFieldName: text

# Parameters related to the Secret used for authentication when pulling images from ACR.
acrSecret:
  secretName: acr-secret        # Name of the created secret

# Parameters regarding mounting Azure File share containing scripts to run in pods.
scriptsMounting:
  enabled: true                                           # Whether or not to enable mounting
  volumePath: mcp_server                                  # Path to a folder in Volume (File share) which will be mounted
  pvcName: azurefiles-pvc                                 # Name of the PVC used for mounting