namespace: rag
jobName: prepare-milvus-db

# Parameters for the 'milvus' dependency. Here we setup Milvus to run in a standalone mode.
milvus:
  cluster:
    enabled: false
  pulsarv3:
    enabled: false
  # Reduce ammount of disk space Milvus is using
  primary:
    persistence:
      enabled: true
      size: 5Gi
  etcd:
    persistence:
      enabled: true
      size: 1Gi
  minio:
    persistence:
      enabled: true
      size: 5Gi
  pulsar:
    bookkeeper:
      persistence:
        enabled: true
        size: 1Gi
    journal:
      persistence:
        enabled: true
        size: 1Gi
    ledgers:
      persistence:
        enabled: true
        size: 1Gi


# Parameters related to the image with the Python script preparing sample data in Milvus db which will be executed by the Job.
image:
  # url - URL of the image in the registry
  url: ${acr_url}/${prepare_milvus_db_image_name}:latest


# Parameters related to the Python script preparing sample data in Milvus db.
app:
  # path - Path in the image of the app
  fileName: prepare_milvus_db.py # Name of the file with the app to run
  folderPath: /app  # Path to the folder containing the app
  # Environment variables used by the Python script
  envVar:
    milvusCollectionName: my_docs
    embeddingFieldName: embedding
    textFieldName: text

# Parameters related to the Secret used for authentication when pulling images from ACR.
acrSecret:
  secretName: acr-secret        # Name of the created secret

# Parameters regarding mounting Azure File share containing scripts to run in pods.
scriptsMounting:
  enabled: true                                           # Whether or not to enable mounting
  volumePath: prepare_milvus_db                           # Path to a folder in Volume (File share) which will be mounted
  pvcName: azurefiles-pvc                                 # Name of the PVC used for mounting