# Secret for accessing a Storage Account with File share where we keep scripts which will be mounted to pods.

{{- if .Values.scriptsMounting.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scriptsMounting.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.scriptsMounting.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.scriptsMounting.storageAccountKey | b64enc }}
{{- end}}